### ISSUE TITLE
Library cannot build with RS485 functionality

### ISSUE THREAD

**Issue by tix** [jnk0le/AVR-UART-lib#3]
Hello and first of all congratulations on an excellent library.
I have been using it for RS-232 and it works flawlessly.
I am now trying to use t with RS-485 features on on an ATtiny841 and I am getting a lot of build errors.
Most of them are 
`lvalue required as left operand of assignment` wherever a call to `___PORT` or `___DDR` is done
I am also getting some 
`pasting "PORT" and "(" does not give a valid preprocessing token`.
My configuration for RS-485 is the following:
`#define RS485_CONTROL0_IOPORTNAME A 
#define RS485_CONTROL0_PIN 1`
Once again thanks a lot for your great library

**Comment by jnk0le** [comment]
Did f3150d57f60953d31b20589fa4395a258225093a fixed your issue ?

Have found an ancient portname instance, but it was giving me a different errors.
