### ISSUE TITLE
Synchronous  

### ISSUE THREAD

**Issue by AminTakhtiNejad** [jnk0le/AVR-UART-lib#5]
hey
thanks for lib
is usart synchronous mode  is implemented?
i wanted to use slave sync mode, where _UCSR1C=(1<<UMSEL1)_  and _baud rate is = 0_
is this possible?

**Comment by jnk0le** [comment]
Actually it is not implemented.

In slave mode clockrate is limited to fcpu/4 by hardware design, and also interrupts won't keep up at such speed.
